def little_grid():
	print '+ - - - - + - - - - +'
	print '|         |         |'
	print '|         |         |'
	print '|         |         |'
	print '|         |         |'
	print '+ - - - - + - - - - +'
	print '|         |         |'
	print '|         |         |'
	print '|         |         |'
	print '|         |         |'
	print '+ - - - - + - - - - +'

def big_grid():
	print '+ - - - - + - - - - + - - - - + - - - - +'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '+ - - - - + - - - - + - - - - + - - - - +'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '+ - - - - + - - - - + - - - - + - - - - +'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '+ - - - - + - - - - + - - - - + - - - - +'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '|         |         |         |         |'
	print '+ - - - - + - - - - + - - - - + - - - - +'

big_grid()
little_grid()
